language: node_js
node_js:
  - "12"
script:
  - npm i -g firebase-tools
  - echo "skipping tests"
before_deploy:
  - cd functions && npm i && cd ..

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "oJhat60AYMR8iw6fveNMkr1eAsNao2DjvEXso0X9mYZEUJjqMOFUEzTTTz+d4GxGNs8MmEoXYTpytenGu/oHh/NnTwe0MvoyhEiX1CIojIO3tpBQ24zOraA6AFC73o9/ZyBj2SgdqMWd+NOsT6G0hWPNChNBYVF+f/obu/5EGPvmTJpP8Zfr4iEDxTBaCXkdxuZGnZXS22QdefeU5QWNEFzEHalMcOfGdHCgCA+QKfYsQBelwH3RO5wzPlljxbbHERuFbv1rhpg/YfCPtnjumuRkn4fZ3k0pGN3ferhtJymE33AnGjQ2aTbTaNXqM2gRDHTiqQdGfuSeBEEqO1/v+G3TWo/9Zefvrau5sflxWNsAPcvY33TmUQrB4CGJFi+A0inN6nQX7Xc9iafuGSGrnIyYWSgglfwdaxgjX/xmh8gaZTYV9saR5KjuJvQWs2n6IihRSKFtTxdUQLmiYKA6sF0YjXE34apwYe7AEDQID/Z6ABHS47KTYvGksUGeVabAj268LlCeNAXAsHxHGcn2eF515PAFoW3PZnQUMpkwm3xDGCb3EtkRM0USrArKT7w3Tx/x4ESAjSBY1VV8BbI9Z/urq5OWlTXXy5I3REbUPSFQTL5/aATzDRq43V/NZCblKNRSj5CTLavz7XICQu5EZHz/QATRtz2bYcAYy4VhtiY="

